services:
  airprint:
    container_name: t426w-airprint
    image: royzheng/t426w:avahi
    platform: linux/amd64
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      CUPSADMIN: admin
      CUPSPASSWORD: admin
      TZ: Asia/Shanghai
    volumes:
      - "./services:/services"
      - "./config:/config"
